### ISSUE TITLE
io package dependency error

### ISSUE THREAD

**Issue by dar-tau** [shraga89/ontobuilderDev#10]
Hello, 
there's a dependency error when I run `mvn install` with the package "ontobuilder.io-2.0-20210925.122618-1.jar":

```
[ERROR] Failed to execute goal on project ontobuilder.io: Could not resolve dependencies for project 
ac.technion.schemamatching:ontobuilder.io:jar:2.0-SNAPSHOT: Failed to collect dependencies at javax.wsdl:wsdl4j:jar:1.5.1: 
Failed to read artifact descriptor for javax.wsdl:wsdl4j:jar:1.5.1: Could not transfer artifact javax.wsdl:wsdl4j:pom:1.5.1 from/to
Talan (https://nexus.talanlabs.com/content/repositories/releases/): authentication failed for
https://nexus.talanlabs.com/content/repositories/releases/javax/wsdl/wsdl4j/1.5.1/wsdl4j-1.5.1.pom, status: 401 Unauthorized
```

**Comment by tomersagi** [comment]
This does not make sense. I fixed this a while ago already:

https://github.com/shraga89/ontobuilderDev/commit/0774408abd18e0cf1b3d252e41f2531ef2bdf024

Are you on the maven branch?
Please post the output of running `git log`

**Comment by tomersagi** [comment]
Could not reproduce the error. Not a bug, usage issue. Awaiting user feedback.

**Comment by tomersagi** [comment]
The problem is traced to the fact that GitHub dies not update builds in snapshot packages:

https://github.community/t/github-package-snapshot-build-number-not-updating/14689/18

Bumping version numbers to 2.0.1 on all packages. From now on, new package deployments need to bump the version number.
